image: registry.gitlab.com/dark-dank/foundry:0.1

stages:
    - build
    - deploy

build_app:
    stage: build
    script:
        - npm i
    tags:
        - docker

deploy_staging:
    stage: deploy
    environment:
        name: staging
        url: https://whos-around-staging.herokuapp.com/
    script:
        - echo "DB_URI=test-uri" > .env
        - dpl --provider=heroku --app=whos-around-staging --api-key=$HEROKU_STAGING_API_KEY --skip_cleanup=true
    tags:
        - docker
    except:
        - master

deploy_production:
    stage: deploy
    environment:
        name: production
        url: https://whos-around.herokuapp.com/
    script:
        - dpl --provider=heroku --app=whos-around --api-key=$HEROKU_STAGING_API_KEY
    tags:
        - docker
    only:
        - master
